<%-- 
    Document   : index
    Created on : 2014-7-7, 14:27:54
    Author     : xy
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>

<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Data-mining Based Expert Platform for the Spectral Inspection</title>
    <link rel="stylesheet" href="resources/css/style.css" type="text/css">
    <script type="text/javascript" src="resources/js/jquery-1.8.3.js"></script>
  </head>
  <body>
    <jsp:include page="jsp/layout/header.jsp"/>
    <div id="contents">
      <div id="adbox">
        <div class="wrapper clearfix">
          <div class="info">
            <h1></h1>
            <p></p>
          </div>
        </div>
        <div class="highlight">
          <h2 style="font-size: 30px;">Data-mining Based <i>Expert Platform</i> for the Spectral Inspection</h2>
        </div>
      </div>
      <div class="body clearfix">
        <div class="click-here">
          <h1>Expert Platform!</h1>
          <a href="user/login" class="btn2"><span style="color: red; font-size: 16px; font-weight: bold;">GET STARTED!</span></a>
        </div>
        <p style="font-size:14px;">
          With the telescopes established and the surveys ongoing, such as the Guoshoujing telescope (LAMOST, Zhao 1999), more and more spectra are collected and released. Unfortunately, except the qualified data, there still exist many spectra unclassified by the automated pipeline. Usually most of these spectra are too low SNR to be classified because of the limited magnitude of the instruments or other reasons. Some important new discoveries are probably hidden in these unknown spectra. Therefore, we should not give up these seemingly useless data, even though they are quite defective. How to handle these unknown spectra is one of the biggest challenges to the modern statistics and data mining techniques as well as eyeball check. In order to ensure the accuracy of the results, we have to motivate experts to check these spectra by visual inspection. Owing to huge amount of such spectra generated continuously by the large sky surveys, it will spend much time and efforts to check spectra one by one. Consequently, a platform to efficiently manage and coarsely classify these unqualified data is in great requirement for the large surveys.
        </p><p style="font-size:14px;">
          We propose a data-mining based platform to assist experts to inspect the increasing amount of spectra with low signal to noise ratio (SNR) generated by large sky surveys. The platform includes three layers: data-mining layer, data-node layer and expert layer. It is similar to the GalaxyZoo project and will be VO-compatible. The preliminary experiment suggests that this platform can play an effective role in managing the spectra and assisting the experts to inspect a large number of spectra with low SNR.</p>
         <p style="font-size:14px;">
          By the way, you should learn some knowledge about three kinds of spectra before the classification via the data-mining techniques.Here are some basic information you should read carefully, you can look for more other information by yourself on the Internet:
          </p>
      </div>
    </div>
    <jsp:include page="jsp/layout/footer.jsp"/>   
  </body>
</html>
